### ISSUE TITLE
QuitBit support for -- command line options for other programs

### ISSUE THREAD

**Issue by hvyarms** [longjoel/quitbit#8]
Trying to run QuitBit with a program that only accepts command line parameters that begin with -- will fail passing those parameters.  The only way I could get QuitBit to work for my program was to modify the .cs file directly to append the parameters directly after the rside switch for the parameters section and then recompile making a "custom" executable for this single program.  Every time I want to modify the parameters I have to recompile with this option.  Love the program so wanted to report in case there is a way to modify somehow like by passing a control character to represent -- for these programs.

**Comment by MiRIr** [comment]
I'm not completely sure this will solve your issue, but I would try changing "--" to "+" so it doesn't contradict with anything. Line 292 contains this code:

**string[] stringElements = clString.Split(new string[] { "--" }, StringSplitOptions.RemoveEmptyEntries);**

Changing this line to:

**string[] stringElements = clString.Split(new string[] { "+" }, StringSplitOptions.RemoveEmptyEntries);**

Will make your QuitBit use + instead of --. For example:

**qb.exe +controller=2 +buttons=2+0+1 +exec=c:\emulators\nes\nes.exe +params=c:\roms\nes\mario.nes**

**Comment by hvyarms** [comment]
Good idea - I think I'll just modify the control character to be three dashes since I can't imagine another program ever doing that and will call it a day :).  I don't think the + would work since that is used for other things (like chaining button presses together).

**Comment by MiRIr** [comment]
You're right about the + sign. I haven't looked at this program in a few months and that would definitely break things. --- should be a pretty unique control character and will hopefully solve your issue.

**Comment by hvyarms** [comment]
Yup - works like a charm.  Thanks for the idea :)!
